### ISSUE TITLE
Umbrella Issue: refactor commands to split flags from options

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubectl#1046]
Currently most or even all of the commands have an `*Options` structure holding all of the data needed to run a command and three main methods `Complete` (finishing `*Options` struct), `Validate` (validating `*Options` struct) and `Run` (actual code behind the command). The current problem is that these `*Options` struct is tightly coupled with flags, but we'd like to split these. 

A perfect example is [wait command](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/wait/wait.go).

This issue should serve as a synchronization point.

/cc @eddiezane @seans3

**Comment by eddiezane** [comment]
/remove-help
/remote-good-first-issue

Holding off on this until we scope better and trial a few to confirm it's what we want.

**Comment by eddiezane** [comment]
@soltysh looking at log and get

**Comment by eddiezane** [comment]
@rikatz will take basic create

**Comment by eddiezane** [comment]
@KnVerey to look at drain or describe

**Comment by eddiezane** [comment]
@eddiezane will look at a simple config command

**Comment by rikatz** [comment]
/assign
So I wont forget :)

**Comment by ihcsim** [comment]
i can do `attach`.

**Comment by pacoxu** [comment]
A simple summary:
- [x] -  wait  ✅    a perfect example
- [ ] -  [**WIP**]create  @lauchokyip & rikatz  https://github.com/kubernetes/kubernetes/pull/101736 
- [ ] -  logs and get @soltysh
- [ ] -  apply @SaiHarshaK 
- [ ] -  config @eddiezane
- [ ] -  drain/describe @KnVerey
- [ ] -  attach @ihcsim

**Comment by eddiezane** [comment]
@BigaDev will take a look at scale

**Comment by MadhavJivrajani** [comment]
/lifecycle frozen
Considering this is a long term tracking issue :)

**Comment by jaehnri** [comment]
/assign 

I'll refactor `label` :)

**Comment by PuneetPunamiya** [comment]
@KnVerey Have you started to refactor the describe command ?

**Comment by PuneetPunamiya** [comment]
@soltysh Based on the slack conversation, I'm picking up the describe command, thanks!

cc @KnVerey 

/assign

Refactoring `describe` command

**Comment by varksvader** [comment]
Hey! I was wondering if you guys needed more help on this issue. I'm happy to pick up a command and start working on it.

**Comment by varksvader** [comment]
/assign

Talked to owner of issue. Grabbing `drain` to refactor.

**Comment by harshitasao** [comment]
I'll refactor `create`
/assign

**Comment by lauchokyip** [comment]
@harshitasao , I think I finished `create`  a while ago (https://github.com/kubernetes/kubernetes/pull/101736),  just waiting for review, would you be able to pick other command to refactor instead?

**Comment by brunopecampos** [comment]
/assign

I'll do diff

**Comment by brunopecampos** [comment]
/assign

I'll do diff

**Comment by varshaprasad96** [comment]
I can work on the refactoring of [expose](https://github.com/kubernetes/kubectl/tree/master/pkg/cmd/expose) command.

**Comment by gxwilkerson33** [comment]
@soltysh @eddiezane  I am working on refactoring of Run command. Currently id does not follow Complete, Validate, Run. Validate seems to be being handled within the Run function. Should i make that refactor also, to make Validate function and remove this functionality from the Run function?
