### ISSUE TITLE
Kubectl Independence: Move packages from `k8s.io/kubernetes/pkg/kubectl` to `k8s.io/kubectl/pkg`

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubectl#133]
Rather than moving everything from Kubectl directly to a new repo, let's move packages that could be use either by Kubectl or by any other kubernetes client application, to `k8s.io/kubectl`.

I'll try to keep track of the packages moved/to be moved in that issue (help wanted):

- [ ] #135 Move `k8s.io/kubernetes/pkg/kubectl/apply` to `k8s.io/kubectl/pkg/apply`
- [ ] #136 Move `k8s.io/kubernetes/pkg/kubectl/explain` to `k8s.io/kubectl/pkg/explain`
- [ ] #137 Move `k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi` to `k8s.io/kubectl/pkg/openapi` 

The goal is not to copy-paste the code and call it the day, but to take that opportunity to:
- Add missing tests,
- Refactor the code to have clean interfaces, prune most dependencies,
- Add more tests,
- Document the interface properly, make sure they look nice on `godoc.org`,
- Add test-examples for the documentation

~~Once the code is copied in that repo, it needs to be vendored in `k8s.io/kubernetes` and replaced there.~~

@mengqiy wrote a proposal: https://docs.google.com/document/d/1yba5jRJSVf1IIXYBO11N8nHbwTbzkDFDssADIC4nbig/edit?usp=sharing
