### ISSUE TITLE
Improve kubectl built-in help

### ISSUE THREAD

**Issue by Parkofadown** [kubernetes/kubectl#1632]
This is an umbrella issue to manage improvement requests in single issue. 

```[tasklist]
### Tasks
- [ ] [Improvement for k8s.io/docs/reference/kubectl/generated/kubectl_cordon/](https://github.com/kubernetes/kubectl/issues/1632)
- [ ] [Improvement for k8s.io/docs/reference/kubectl/generated/kubectl_events/](https://github.com/kubernetes/kubectl/issues/1635)
- [ ] [Improvement for k8s.io/docs/reference/kubectl/generated/kubectl_kustomize/](https://github.com/kubernetes/kubectl/issues/1636)
- [ ] [Improvement for k8s.io/docs/reference/kubectl/generated/kubectl_label/](https://github.com/kubernetes/kubectl/issues/1637)
- [ ] [Improve behavior of kubectl options](https://github.com/kubernetes/kubectl/issues/1638)
```

**Comment by sftim** [comment]
@Parkofadown this issue has a new URL now, but it's still in a way the “same” issue

**Comment by ardaguclu** [comment]
This is a doc improvement which is a good thing
/triage accepted
/priority backlog
@Parkofadown would you like to open a PR?

**Comment by Parkofadown** [comment]
> This is a doc improvement which is a good thing /triage accepted /priority backlog @Parkofadown would you like to open a PR?

@ardaguclu I would love to open a PR but I do not know your timeline for improvement. I currently work full-time 7:30AM - 3:30 PM EST and provide for 5 people in my household after that.

**Comment by ardaguclu** [comment]
Also this https://github.com/kubernetes/kubectl/issues/1634

**Comment by ardaguclu** [comment]
and this https://github.com/kubernetes/kubectl/issues/1639

**Comment by ah8ad3** [comment]
I suggest if you agree we can make this good first issue, for some one that wants to fix them.

**Comment by sftim** [comment]
Umbrella issues _don't_ make good first issues; see https://www.kubernetes.dev/docs/guide/help-wanted/#good-first-issue

**Comment by Parkofadown** [comment]
I don't agree that this is a good first issue. Someone would have to know how to program a terminal and be very careful to not make a mistake

**Comment by Antraxmin** [comment]
I'd like to work on this umbrella issue by tackling each sub-issue one by one - would that be acceptable?
