### ISSUE TITLE
Remove Kubectl dependencies on kubernetes/pkg/api and kubernetes/pkg/apis

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#83]
Background:
Kubernetes resource structs have 2 versions - an internal version and an external version.  Kubectl should only depend on the external versions so that it can be moved into its own repo and be maintained independently from the server.  To do this, we must replace instances where an internal type and client is used with the external type and client.

An example PR of how to do this can be found here: https://github.com/kubernetes/kubernetes/pull/54157

**NOTE**: That PR is unmerged and someone should clone it and then complete it by fixing any broken tests and sending it for review.

List of api pkgs that must be removed:

- [ ] k8s.io/kubernetes/pkg/api
- [ ] k8s.io/kubernetes/pkg/api/resource
- [ ] k8s.io/kubernetes/pkg/api/v1
- [ ] k8s.io/kubernetes/pkg/api/v1/pod
- [ ] k8s.io/kubernetes/pkg/api/validation
- [ ] k8s.io/kubernetes/pkg/apis/apps
- [ ] k8s.io/kubernetes/pkg/apis/batch
- [ ] k8s.io/kubernetes/pkg/apis/extensions #92
- [ ] k8s.io/kubernetes/pkg/apis/policy #90
- [ ] k8s.io/kubernetes/pkg/apis/rbac #91 @shiywang 

To get started:

- If something has an issue already, assign yourself to it if no one is on it
- If something doesn't have an issue, file an issue for it and add it as a comment to this issue.

Strategy:

- Look for import statements under packages under pkg/kubctl that reference the above packages
- Look for the simplest ones to remove where the external type can be used instead with an external client
- Create a new issue for that package and update this issue with a comment containing the issue number
- Fix them and send a PR

**Comment by dims** [comment]
@quinton-hoole - seems like a list of things that can be done mechanically here. if we have some folks to help out.

**Comment by WanLinghao** [comment]
Is  this job  going  by some  kind of order? @pwittrock

**Comment by m1093782566** [comment]
@quinton-hoole @dims I can be the volunteer.

**Comment by seans3** [comment]
Closing this in favor of the more general: 
https://github.com/kubernetes/kubectl/issues/80
