### ISSUE TITLE
Meta/Umbrella: Improve `pkg/kubectl/resource`unit / integration test coverage and structure

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubectl#93]
**Note:** The items can be completed incrementally, but are not easy to parallelize.  Taking this issue does not commit you to completing all of the items, just the next ones on the list. 

The [pkg/kubectl/resource](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/resource) is critically important, but we have very little unit or integration test coverage for it and even less documentation.

- [ ] Read the libraries and document the functions and code
- [ ]  Audit the which functions are covered by unit tests, integration tests and aren't covered at all
  - Run go test coverage tools to figure this out, attach results to the issue
- [ ] Write unit tests for functions that aren't tested at all
  - Send multiple small PRs instead of 1 big one
- [ ] Write unit tests for functions that are only tested with integration tests
  - Send multiple small PRs instead of 1 big one
- [ ] Write integration tests for anything with weak coverage using tmp files

**Comment by mudejar** [comment]
@mengqiy @seans3 @pwittrock I'd like to take this issue as a first task to contribute if no one else has already been assigned to it

**Comment by pwittrock** [comment]
@mudejar It is all yours.  Please work with @droot

**Comment by adshmh** [comment]
cc @seans3 @mengqiy @pwittrock I just submitted a PR on this as a start. Would appreciate it if you could review it.
